In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix

In [14]:
df=pd.read_csv("D:/DS/AI ML DL/Let'sUpgrade/Class Materials/day 24/train.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [16]:
le=preprocessing.LabelEncoder()
le.fit(df['Sex'])
df['Sex']=le.transform(df['Sex'])
le.fit(df['Embarked'])
df['Embarked']=le.transform(df['Embarked'])

In [18]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [20]:
df1=df.drop(['Name','Ticket','Cabin','PassengerId'],axis=1)
df1.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [22]:
df1.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [24]:
df1.count()

Survived    889
Pclass      889
Sex         889
Age         889
SibSp       889
Parch       889
Fare        889
Embarked    889
dtype: int64

In [26]:
# Total count is 889 so Test count=
889*0.3

266.7

In [28]:
# & Train count =
889*0.7

622.3

In [30]:
from sklearn import svm

In [ ]:
# x = df1.drop(['Pclass'], axis=1)

In [ ]:
# y=df1['Pclass']

In [34]:
def svm(i):
    x=df1.drop([i],axis=1)
    y=df1[i]
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size =0.3, random_state=0)
    clf.fit(x_train,y_train)
    y_pred=clf.predict(x_test)
    accuracy=accuracy_score(y_test,y_pred,normalize=True)
    cmat=confusion_matrix(y_test, y_pred)
    print("Dependent variable = ",i)
    print("Accuracy = ",accuracy)
    print("Confusion Matrix = \n",cmat)
    print("--------------------------------------------------------------------------------------------------")
    return accuracy

In [36]:
var=['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Embarked']
scores=[]
for i in var:
    svm(i)
    scores.append(svm(i))
print(scores)

Dependent variable =  Survived
Accuracy =  0.7415730337078652
Confusion Matrix = 
 [[124  33]
 [ 36  74]]
--------------------------------------------------------------------------------------------------
Dependent variable =  Survived
Accuracy =  0.7415730337078652
Confusion Matrix = 
 [[124  33]
 [ 36  74]]
--------------------------------------------------------------------------------------------------
Dependent variable =  Pclass
Accuracy =  0.9026217228464419
Confusion Matrix = 
 [[ 64   4   2]
 [  4  36   9]
 [  1   6 141]]
--------------------------------------------------------------------------------------------------
Dependent variable =  Pclass
Accuracy =  0.9026217228464419
Confusion Matrix = 
 [[ 64   4   2]
 [  4  36   9]
 [  1   6 141]]
--------------------------------------------------------------------------------------------------
Dependent variable =  Sex
Accuracy =  0.7265917602996255
Confusion Matrix = 
 [[ 66  32]
 [ 41 128]]
-------------------------------------

In [53]:
pd.DataFrame(np.array(scores),np.array(var),columns=["Accuracy"])

Accuracy
Survived  0.741573
Pclass    0.902622
Sex       0.726592
SibSp     0.749064
Parch     0.797753
Embarked  0.767790