# 1. Create a 3x3x3 array with random values 

In [7]:
import numpy as np
np.random.random((3,3,3))

array([[[0.50223522, 0.40751215, 0.132599  ],
        [0.77167708, 0.57533227, 0.03284604],
        [0.17509104, 0.48432695, 0.40993065]],

       [[0.76902802, 0.60034327, 0.63544772],
        [0.2677126 , 0.22461009, 0.77129968],
        [0.96027348, 0.7770651 , 0.70610092]],

       [[0.65013947, 0.52514871, 0.91294525],
        [0.90429648, 0.11843579, 0.83297527],
        [0.51614845, 0.47826466, 0.91129543]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [13]:
np.diag(np.arange(1,5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [37]:
a = np.zeros((8,8), int)
a[0::2, 0::2] = 1 # Start:Stop:Step # Row, Column
a[1::2, 1::2] = 1
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

# 4. Normalize a 5x5 random matrix

In [41]:
b = np.random.random((5,5))
bmax, bmin = b.max(), b.min()
b = (b - bmin) / (bmax - bmin)
b

array([[0.14814439, 0.73711078, 0.74526486, 0.62921491, 0.45992502],
       [0.        , 0.53632039, 0.41906356, 0.42911932, 0.41727014],
       [0.1017589 , 0.02164546, 0.85573762, 0.63840934, 0.11401443],
       [0.31627345, 0.54071102, 0.35807116, 1.        , 0.02491034],
       [0.7575929 , 0.46921535, 0.95307047, 0.55247446, 0.3101846 ]])

# 5.  How to find common values between two arrays?

In [45]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr2 = np.array([9, 10, 4, 34, 6, 7, 8])
np.intersect1d(arr1, arr2) # not work for 2d,3d

array([4, 6, 7])

# 6.How to get the dates of yesterday, today and tomorrow?

In [65]:
Yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday:", Yesterday)
Today = np.datetime64('today', 'D')
print("Today:", Today)
Tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow:", Tomorrow)

Yesterday: 2020-07-26
Today: 2020-07-27
Tomorrow: 2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [71]:
c = np.random.randint(0,2,6).reshape(3,2)
print(c)
d = np.random.randint(0,2,6).reshape(3,2)
print(d)
print(np.allclose(c,d))


[[0 0]
 [1 1]
 [1 0]]
[[1 0]
 [0 1]
 [0 0]]
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [107]:
e = np.random.randint(0,100,10)
print(e)
e[e.argmax()] = 0
print(e)


[55 44 79 37 47 84 37 98 32 20]
[55 44 79 37 47 84 37  0 32 20]


# 9. How to print all the values of an array?

In [109]:
np.set_printoptions(threshold=np.inf)
x = np.arange(100)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


# 10.Subtract the mean of each row of a matrix

In [135]:
np.random.seed(0)
p = np.random.rand(10,5)
print(p)
mean_row = p.mean(axis=1, keepdims=True) # mean of each row
print("\nSubtract the mean of each row: ")
print(p-mean_row)


[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]
 [0.63992102 0.14335329 0.94466892 0.52184832 0.41466194]
 [0.26455561 0.77423369 0.45615033 0.56843395 0.0187898 ]
 [0.6176355  0.61209572 0.616934   0.94374808 0.6818203 ]
 [0.3595079  0.43703195 0.6976312  0.06022547 0.66676672]
 [0.67063787 0.21038256 0.1289263  0.31542835 0.36371077]]

Subtract the mean of each row: 
[[-0.01824734  0.14812852  0.03570253 -0.02217766 -0.14340605]
 [-0.01857761 -0.22688451  0.22730128  0.29919104 -0.2810302 ]
 [ 0.21466559 -0.04816452 -0.00901488  0.3485372  -0.50602338]
 [-0.43049799 -0.49740889  0.31499256  0.26052946  0.35238486]
 [ 0.35100637  0.17154659 -0.16613261  0.1529172  -0.50933755]
 [ 0.10703032 -0.38953741  0.41177822 -0.01104238 -0.11822876]
 [-0.151

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [162]:
v = np.ones(10)
print(v)
np.random.seed(0)
i = np.random.randint(0,len(v),20)
print(i)
v += np.bincount(i, minlength=len(v))
print(v)
# i = 0 to 9 so occurance of 0 in i = 1 + v i.e. 1 =2, occ of 1 in 1 = 2 + 1(v) = 3, occ of 2 in i = 1 + 1(v) = 2 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 0 3 3 7 9 3 5 2 4 7 6 8 8 1 6 7 7 8 1]
[2. 3. 2. 4. 2. 3. 3. 5. 4. 2.]


# 12.How to get the diagonal of a dot product?

In [167]:
d = np.random.randint(0,10,(3,3))
print(d)
f = np.random.randint(0,10,(3,3))
print(f)

# np.diag(np.dot(d,f))
# np.sum(d * f.T, axis=1)
np.einsum('ij,ji->i', d, f) # faster

[[3 0 5]
 [0 1 2]
 [4 2 0]]
[[3 2 0]
 [7 5 9]
 [0 2 7]]


array([ 9,  9, 18])

# 13.How to find the most frequent value in an array?

In [169]:
g = np.random.randint(0,10, 25)
print(g)
print("Most Frequent Value:", np.bincount(g).argmax())

[9 6 5 3 1 8 0 4 9 6 5 7 8 8 9 2 8 6 6 9 1 6 8 8 3]
Most Frequent Value: 8


# 14.How to get the n largest values of an array

In [177]:
h = np.arange(200)
np.random.shuffle(h)
print(h)
n = 5 # 5 largest values

# print(n, "largest values:", h[np.argsort(h)[-n:]])
print(h[np.argpartition(-h,n)[:n]]) # fast

[196 151 140 160  31 115 143 157 134 180  41  12  19 133 186 192  72 175
  69 182 138 189 127 129  52 150 168  13  35  92  95  56  70 103  88  74
 142 193 123 162 104  46  96 122  39  90  50 149  73  48 101 137  85  49
  76 174 124 165 159  36 187  57  99 106 111  18   8 135 128 166   4 105
  51 120  40   9 113  66  47  77 178 185 163  15   1  79  38  94  63 126
  59 181  91 130 112 100 132 184  44  93   0 195 144  30 197 107 109  78
 171 169 156   2 147 198  75 188 146 183  53   3 110  64  89  26  27 191
 177 145 170  28 164 152  61  60 114 141 199 173 176  87 179  97  33  16
  98  84   7 108  37 154 116 131 121  25  83 118  54 153 161  42  58  71
 158 139  29  62  10  82 172   5 136  17  86  24 167  45  68  21  22  65
  32  34  23 148 102 155 194 117  80 190  14 119  20  67  43 125  55  81
  11   6]
[199 198 196 197 195]


# 15.How to create a record array from a regular array?

In [181]:
j = np.array([('Numpy', 2.5, 3), ('Python', 3.6, 2)])
k = np.core.records.fromarrays(j.T, names= 'col1, col2, col3', formats= 'S8, f8, i8')
k

rec.array([(b'Numpy', 2.5, 3), (b'Python', 3.6, 2)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])